// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Ajax_Lab01.Models;

public partial class Address
{
    public int Id { get; set; }

    public string? City { get; set; }

    public string? SiteId { get; set; }

    public string? Road { get; set; }
}